from django.core.management.base import BaseCommand
from college.models import College, Course
from decimal import Decimal

class Command(BaseCommand):
    help = 'Populate the database with sample college and course data for Nepal.'

    def handle(self, *args, **kwargs):
        # Clear existing data
        College.objects.all().delete()
        Course.objects.all().delete()

        # Sample course data
        courses_data = [
            {"name": "ACCA", "objectives": "Train professionals in accounting and finance.", "advantages": "Globally recognized certification."},
            {"name": "BBS", "objectives": "Provide business studies education.", "advantages": "Foundation for business careers."},
            {"name": "BBA", "objectives": "Develop management and leadership skills.", "advantages": "Versatile business degree."},
            {"name": "BBA in Accounting & Finance", "objectives": "Specialized business education in finance.", "advantages": "High demand in financial sectors."},
            {"name": "BBA in Marketing", "objectives": "Teach marketing strategies and consumer behavior.", "advantages": "Career in advertising and sales."},
            {"name": "B.Sc. (Hons) in Computing", "objectives": "Train in software development and IT.", "advantages": "High demand in tech industry."},
            {"name": "BHM", "objectives": "Educate in hospitality and hotel management.", "advantages": "Career in tourism and hospitality."},
            {"name": "BCA", "objectives": "Develop computer application skills.", "advantages": "Entry to IT and software development."},
            {"name": "BASW", "objectives": "Train in social work practices.", "advantages": "Career in social services."},
            {"name": "BA in Psychology", "objectives": "Study human behavior and mental processes.", "advantages": "Career in counseling and research."},
            {"name": "BBM", "objectives": "Focus on business management.", "advantages": "Prepares for managerial roles."},
            {"name": "+2 Science", "objectives": "Provide foundational science education.", "advantages": "Pathway to medical and engineering fields."},
            {"name": "+2 Management", "objectives": "Introduce business and management concepts.", "advantages": "Foundation for business studies."},
            {"name": "B.Tech Food Technology", "objectives": "Train in food science and technology.", "advantages": "Career in food industry."},
            {"name": "BIT", "objectives": "Educate in information technology.", "advantages": "High demand in IT sectors."},
            {"name": "BE Civil", "objectives": "Train in civil engineering principles.", "advantages": "Career in infrastructure development."},
            {"name": "BE Computer", "objectives": "Develop computer engineering skills.", "advantages": "High demand in tech industry."},
            {"name": "BTTM", "objectives": "Educate in tourism management.", "advantages": "Career in travel and tourism."},
            {"name": "MBA", "objectives": "Advanced business management education.", "advantages": "Leadership roles in business."},
            {"name": "BSc Physics", "objectives": "Study physical sciences.", "advantages": "Career in research and academia."},
        ]

        # Create Course objects
        course_objects = {}
        for course_data in courses_data:
            course = Course.objects.create(**course_data)
            course_objects[course_data["name"]] = course

        # Expanded college data for Nepal with additional fields
        colleges_data = [
            {
                "name": "Certified College of Accountancy (CCA)",
                "affiliation": "National Examination Board (NEB) & ACCA Global",
                "course_names": ["ACCA", "BBS"],
                "budget": Decimal("150000.00"),  # ~$1100 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.cca.edu.np",
                "scholarship": "Merit-based scholarships for top ACCA performers",
                "contact_info": "info@cca.edu.np, +977-1-4251234",
                "latitude": 27.7172,
                "longitude": 85.3240,
                "facilities": "Library, computer labs, seminar halls, Wi-Fi",
            },
            {
                "name": "Tribhuvan University - Kirtipur Campus",
                "affiliation": "Tribhuvan University",
                "course_names": ["BBS", "BBA", "BASW", "BA in Psychology", "BSc Physics"],
                "budget": Decimal("80000.00"),  # ~$590 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kirtipur Municipality",
                "website": "http://www.tu.edu.np",
                "scholarship": "Need-based and merit-based scholarships available",
                "contact_info": "info@tu.edu.np, +977-1-4331234",
                "latitude": 27.6833,
                "longitude": 85.2833,
                "facilities": "Library, science labs, hostels, sports facilities",
            },
            {
                "name": "Kathmandu University - School of Management",
                "affiliation": "Kathmandu University",
                "course_names": ["BBA", "BBA in Marketing", "BBM", "MBA"],
                "budget": Decimal("300000.00"),  # ~$2200 USD
                "province": "Bagmati",
                "district": "Lalitpur",
                "municipality": "Lalitpur Metropolitan City",
                "website": "http://www.ku.edu.np",
                "scholarship": "Merit-based scholarships for top students",
                "contact_info": "som@ku.edu.np, +977-1-5251234",
                "latitude": 27.6181,
                "longitude": 85.3247,
                "facilities": "Modern library, computer labs, Wi-Fi, cafeteria",
            },
            {
                "name": "Pokhara University - School of Business",
                "affiliation": "Pokhara University",
                "course_names": ["BBA", "BBA in Accounting & Finance", "BHM", "BTTM"],
                "budget": Decimal("250000.00"),  # ~$1850 USD
                "province": "Gandaki",
                "district": "Kaski",
                "municipality": "Pokhara Metropolitan City",
                "website": "http://www.pu.edu.np",
                "scholarship": "Scholarships for economically disadvantaged students",
                "contact_info": "info@pu.edu.np, +977-61-561234",
                "latitude": 28.2096,
                "longitude": 83.9856,
                "facilities": "Library, computer labs, hostel, sports ground",
            },
            {
                "name": "Nepal Engineering College",
                "affiliation": "Pokhara University",
                "course_names": ["BE Civil", "BE Computer"],
                "budget": Decimal("350000.00"),  # ~$2600 USD
                "province": "Bagmati",
                "district": "Bhaktapur",
                "municipality": "Changunarayan Municipality",
                "website": "http://www.nec.edu.np",
                "scholarship": "Merit-based and need-based scholarships",
                "contact_info": "info@nec.edu.np, +977-1-5221234",
                "latitude": 27.7017,
                "longitude": 85.4250,
                "facilities": "Engineering labs, library, Wi-Fi, transportation",
            },
            {
                "name": "St. Xavier’s College, Maitighar",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["+2 Science", "+2 Management", "BSc Physics", "BASW"],
                "budget": Decimal("120000.00"),  # ~$890 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.sxc.edu.np",
                "scholarship": "Scholarships for top +2 and undergraduate students",
                "contact_info": "info@sxc.edu.np, +977-1-4221234",
                "latitude": 27.6936,
                "longitude": 85.3190,
                "facilities": "Science labs, library, sports facilities, Wi-Fi",
            },
            {
                "name": "Ace Institute of Management",
                "affiliation": "Pokhara University",
                "course_names": ["BBA", "BBA in Marketing", "MBA"],
                "budget": Decimal("400000.00"),  # ~$2950 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.ace.edu.np",
                "scholarship": "Merit-based scholarships for MBA and BBA",
                "contact_info": "info@ace.edu.np, +977-1-4411234",
                "latitude": 27.6890,
                "longitude": 85.3210,
                "facilities": "Modern classrooms, library, Wi-Fi, seminar halls",
            },
            {
                "name": "Himalayan WhiteHouse International College",
                "affiliation": "Purbanchal University",
                "course_names": ["BBA", "BHM", "BIT", "BE Computer"],
                "budget": Decimal("280000.00"),  # ~$2070 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.hwic.edu.np",
                "scholarship": "Scholarships for IT and hospitality students",
                "contact_info": "info@hwic.edu.np, +977-1-5531234",
                "latitude": 27.7160,
                "longitude": 85.3160,
                "facilities": "Computer labs, library, hostel, cafeteria",
            },
            {
                "name": "Kantipur College of Management and Information Technology",
                "affiliation": "Tribhuvan University",
                "course_names": ["BCA", "BIT", "BBA"],
                "budget": Decimal("200000.00"),  # ~$1480 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.kcmit.edu.np",
                "scholarship": "Merit-based scholarships for IT students",
                "contact_info": "info@kcmit.edu.np, +977-1-5571234",
                "latitude": 27.7000,
                "longitude": 85.3200,
                "facilities": "Computer labs, library, Wi-Fi, seminar rooms",
            },
            {
                "name": "Nepal College of Travel and Tourism Management",
                "affiliation": "Purbanchal University",
                "course_names": ["BHM", "BTTM"],
                "budget": Decimal("180000.00"),  # ~$1330 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.ncttm.edu.np",
                "scholarship": "Scholarships for tourism students",
                "contact_info": "info@ncttm.edu.np, +977-1-4261234",
                "latitude": 27.7050,
                "longitude": 85.3250,
                "facilities": "Training kitchens, library, Wi-Fi, mock hotel",
            },
            {
                "name": "GoldenGate International College",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["+2 Science", "+2 Management", "BSc Physics", "B.Tech Food Technology"],
                "budget": Decimal("110000.00"),  # ~$810 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.goldengate.edu.np",
                "scholarship": "Merit-based and need-based scholarships",
                "contact_info": "info@goldengate.edu.np, +977-1-4471234",
                "latitude": 27.7100,
                "longitude": 85.3100,
                "facilities": "Science labs, library, sports facilities, Wi-Fi",
            },
            {
                "name": "Nepal Mega College",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["BBS", "BBA", "+2 Science", "+2 Management"],
                "budget": Decimal("100000.00"),  # ~$740 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.nepalmega.edu.np",
                "scholarship": "Scholarships for +2 and undergraduate students",
                "contact_info": "info@nepalmega.edu.np, +977-1-4291234",
                "latitude": 27.6950,
                "longitude": 85.3150,
                "facilities": "Library, computer labs, sports ground, cafeteria",
            },
            {
                "name": "Kathmandu Model College",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["BBA", "BBS", "+2 Science", "+2 Management"],
                "budget": Decimal("130000.00"),  # ~$960 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.kmc.edu.np",
                "scholarship": "Merit-based scholarships available",
                "contact_info": "info@kmc.edu.np, +977-1-4421234",
                "latitude": 27.7020,
                "longitude": 85.3180,
                "facilities": "Library, science labs, Wi-Fi, hostel",
            },
            {
                "name": "Islington College",
                "affiliation": "London Metropolitan University (UK)",
                "course_names": ["B.Sc. (Hons) in Computing", "BIT", "BBA"],
                "budget": Decimal("450000.00"),  # ~$3330 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.islington.edu.np",
                "scholarship": "Scholarships for top IT and business students",
                "contact_info": "info@islington.edu.np, +977-1-4431234",
                "latitude": 27.7080,
                "longitude": 85.3230,
                "facilities": "Advanced computer labs, library, Wi-Fi, seminar halls",
            },
            {
                "name": "Padmashree International College",
                "affiliation": "Tribhuvan University",
                "course_names": ["B.Tech Food Technology", "BIT", "BCA"],
                "budget": Decimal("220000.00"),  # ~$1630 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.padmashree.edu.np",
                "scholarship": "Scholarships for food technology and IT students",
                "contact_info": "info@padmashree.edu.np, +977-1-5541234",
                "latitude": 27.6970,
                "longitude": 85.3170,
                "facilities": "Food technology labs, library, Wi-Fi, cafeteria",
            },
            {
                "name": "Thames International College",
                "affiliation": "Tribhuvan University",
                "course_names": ["BBA", "BBS", "BASW", "BA in Psychology"],
                "budget": Decimal("150000.00"),  # ~$1100 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.thamescollege.edu.np",
                "scholarship": "Merit-based and need-based scholarships",
                "contact_info": "info@thamescollege.edu.np, +977-1-4461234",
                "latitude": 27.6900,
                "longitude": 85.3200,
                "facilities": "Library, computer labs, Wi-Fi, seminar halls",
            },
            {
                "name": "Texas College of Management and IT",
                "affiliation": "Lincoln University College (Malaysia)",
                "course_names": ["BBA", "BIT", "BCA"],
                "budget": Decimal("300000.00"),  # ~$2200 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.texascollege.edu.np",
                "scholarship": "Scholarships for IT and management students",
                "contact_info": "info@texascollege.edu.np, +977-1-4451234",
                "latitude": 27.6940,
                "longitude": 85.3220,
                "facilities": "Computer labs, library, Wi-Fi, hostel",
            },
            {
                "name": "Kathford International College of Engineering and Management",
                "affiliation": "Tribhuvan University",
                "course_names": ["BE Civil", "BE Computer", "BCA"],
                "budget": Decimal("320000.00"),  # ~$2370 USD
                "province": "Bagmati",
                "district": "Lalitpur",
                "municipality": "Lalitpur Metropolitan City",
                "website": "http://www.kathford.edu.np",
                "scholarship": "Merit-based scholarships for engineering students",
                "contact_info": "info@kathford.edu.np, +977-1-5201234",
                "latitude": 27.6740,
                "longitude": 85.3240,
                "facilities": "Engineering labs, library, Wi-Fi, transportation",
            },
            {
                "name": "King’s College",
                "affiliation": "Westcliff University (USA)",
                "course_names": ["BBA", "MBA"],
                "budget": Decimal("400000.00"),  # ~$2950 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.kingscollege.edu.np",
                "scholarship": "Scholarships for top business students",
                "contact_info": "info@kingscollege.edu.np, +977-1-4441234",
                "latitude": 27.6920,
                "longitude": 85.3190,
                "facilities": "Modern classrooms, library, Wi-Fi, incubation center",
            },
            {
                "name": "Janamaitri Multiple Campus",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["+2 Science", "+2 Management", "BBS"],
                "budget": Decimal("90000.00"),  # ~$670 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kirtipur Municipality",
                "website": "http://www.janamaitri.edu.np",
                "scholarship": "Need-based scholarships for community students",
                "contact_info": "info@janamaitri.edu.np, +977-1-4331234",
                "latitude": 27.6780,
                "longitude": 85.2850,
                "facilities": "Library, science labs, sports facilities, Wi-Fi",
            },
            {
                "name": "Softwarica College of IT and E-commerce",
                "affiliation": "Coventry University (UK)",
                "course_names": ["B.Sc. (Hons) in Computing", "BIT", "BCA"],
                "budget": Decimal("420000.00"),  # ~$3110 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.softwarica.edu.np",
                "scholarship": "Scholarships for top IT students",
                "contact_info": "info@softwarica.edu.np, +977-1-4431234",
                "latitude": 27.7060,
                "longitude": 85.3150,
                "facilities": "Advanced computer labs, library, Wi-Fi, seminar halls",
            },
            {
                "name": "Nepal College of Information Technology (NCIT)",
                "affiliation": "Pokhara University",
                "course_names": ["BE Civil", "BE Computer", "BCA", "BIT"],
                "budget": Decimal("330000.00"),  # ~$2440 USD
                "province": "Bagmati",
                "district": "Lalitpur",
                "municipality": "Lalitpur Metropolitan City",
                "website": "http://www.ncit.edu.np",
                "scholarship": "Merit-based scholarships for engineering and IT",
                "contact_info": "info@ncit.edu.np, +977-1-5531234",
                "latitude": 27.6720,
                "longitude": 85.3260,
                "facilities": "Engineering labs, computer labs, library, Wi-Fi",
            },
            {
                "name": "New Summit College",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["+2 Science", "+2 Management", "BCA"],
                "budget": Decimal("110000.00"),  # ~$810 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.newsummit.edu.np",
                "scholarship": "Scholarships for +2 and BCA students",
                "contact_info": "info@newsummit.edu.np, +977-1-4471234",
                "latitude": 27.7040,
                "longitude": 85.3170,
                "facilities": "Science labs, library, sports facilities, Wi-Fi",
            },
            {
                "name": "Silver Mountain School of Hotel Management",
                "affiliation": "Queen Margaret University (UK) & CTEVT",
                "course_names": ["BHM", "BTTM"],
                "budget": Decimal("350000.00"),  # ~$2600 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.silvermountain.edu.np",
                "scholarship": "Scholarships for hospitality students",
                "contact_info": "info@silvermountain.edu.np, +977-1-4421234",
                "latitude": 27.7030,
                "longitude": 85.3160,
                "facilities": "Training kitchens, mock hotel, library, Wi-Fi",
            },
            {
                "name": "Public Youth Campus",
                "affiliation": "Tribhuvan University",
                "course_names": ["BBA", "BBS", "MBA"],
                "budget": Decimal("100000.00"),  # ~$740 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.pyc.edu.np",
                "scholarship": "Need-based scholarships available",
                "contact_info": "info@pyc.edu.np, +977-1-4251234",
                "latitude": 27.7010,
                "longitude": 85.3190,
                "facilities": "Library, computer labs, Wi-Fi, cafeteria",
            },
            {
                "name": "Sagarmatha Engineering College",
                "affiliation": "Tribhuvan University",
                "course_names": ["BE Civil", "BE Computer"],
                "budget": Decimal("340000.00"),  # ~$2520 USD
                "province": "Bagmati",
                "district": "Lalitpur",
                "municipality": "Lalitpur Metropolitan City",
                "website": "http://www.sagarmatha.edu.np",
                "scholarship": "Merit-based scholarships for engineering students",
                "contact_info": "info@sagarmatha.edu.np, +977-1-5521234",
                "latitude": 27.6700,
                "longitude": 85.3250,
                "facilities": "Engineering labs, library, Wi-Fi, transportation",
            },
            {
                "name": "DAV College",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["BBA", "BBS", "+2 Science", "+2 Management"],
                "budget": Decimal("120000.00"),  # ~$890 USD
                "province": "Bagmati",
                "district": "Lalitpur",
                "municipality": "Lalitpur Metropolitan City",
                "website": "http://www.davcollege.edu.np",
                "scholarship": "Scholarships for +2 and business students",
                "contact_info": "info@davcollege.edu.np, +977-1-5531234",
                "latitude": 27.6750,
                "longitude": 85.3210,
                "facilities": "Library, science labs, sports facilities, Wi-Fi",
            },
            {
                "name": "Nobel Academy",
                "affiliation": "NEB",
                "course_names": ["+2 Science", "+2 Management"],
                "budget": Decimal("100000.00"),  # ~$740 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.nobelacademy.edu.np",
                "scholarship": "Merit-based scholarships for +2 students",
                "contact_info": "info@nobelacademy.edu.np, +977-1-4781234",
                "latitude": 27.7090,
                "longitude": 85.3180,
                "facilities": "Science labs, library, sports ground, Wi-Fi",
            },
            {
                "name": "Times International College",
                "affiliation": "Tribhuvan University & NEB",
                "course_names": ["BBA", "BBM", "+2 Science", "+2 Management"],
                "budget": Decimal("110000.00"),  # ~$810 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.timescollege.edu.np",
                "scholarship": "Scholarships for +2 and undergraduate students",
                "contact_info": "info@timescollege.edu.np, +977-1-4491234",
                "latitude": 27.6980,
                "longitude": 85.3160,
                "facilities": "Library, computer labs, sports facilities, Wi-Fi",
            },
            {
                "name": "Orchid International College",
                "affiliation": "Tribhuvan University",
                "course_names": ["BCA", "BBM", "BBA"],
                "budget": Decimal("180000.00"),  # ~$1330 USD
                "province": "Bagmati",
                "district": "Kathmandu",
                "municipality": "Kathmandu Metropolitan City",
                "website": "http://www.orchidcollege.edu.np",
                "scholarship": "Merit-based scholarships for IT and business",
                "contact_info": "info@orchidcollege.edu.np, +977-1-4471234",
                "latitude": 27.7070,
                "longitude": 85.3200,
                "facilities": "Computer labs, library, Wi-Fi, seminar halls",
            },
        ]

        # Create College objects and link courses
        for college_data in colleges_data:
            course_names = college_data.pop("course_names")
            college = College.objects.create(**college_data)
            for course_name in course_names:
                college.courses.add(course_objects[course_name])

        self.stdout.write(self.style.SUCCESS(f'Successfully populated {len(colleges_data)} colleges and {len(courses_data)} courses.'))