# Generated by Django 5.2.4 on 2025-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='college_brochures/'),
        ),
        migrations.AddField(
            model_name='college',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='college',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college_images/'),
        ),
        migrations.AddField(
            model_name='college',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='scholarship',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
